version: '3.8'

services:
  db:
    image: postgres:16
    container_name: social-media-feed-postgres-prod
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - social_media_network

  redis:
    image: redis:7-alpine
    container_name: social-media-feed-redis-prod
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata_prod:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - social_media_network

  web:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    container_name: social-media-feed-web-prod
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
    volumes:
      - media_files_prod:/app/media
      - static_files_prod:/app/staticfiles
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - social_media_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: social-media-feed-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_files_prod:/app/staticfiles
      - media_files_prod:/app/media
      - ./ssl:/etc/nginx/ssl
    depends_on:
      web:
        condition: service_healthy
    networks:
      - social_media_network

volumes:
  pgdata_prod:
  redisdata_prod:
  media_files_prod:
  static_files_prod:

networks:
  social_media_network:
    driver: bridge