# Generated by Django 4.2.7 on 2025-08-09 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action", models.CharField(db_index=True, max_length=100)),
                ("resource", models.CharField(db_index=True, max_length=50)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, db_index=True, null=True),
                ),
                ("user_agent", models.TextField(blank=True)),
                (
                    "execution_time_ms",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "activity_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="activity_lo_user_id_d23b30_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="activity_lo_action_0f3584_idx",
                    ),
                    models.Index(
                        fields=["resource", "created_at"],
                        name="activity_lo_resourc_3b4a3f_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="activity_lo_content_edc5bf_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "created_at"],
                        name="activity_lo_ip_addr_4fb53a_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="activity_lo_created_166e11_idx"
                    ),
                ],
            },
        ),
    ]
