# Generated by Django 4.2.7 on 2025-08-08 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_follow"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="followers_count",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="following_count",
        ),
    ]
