name: CI - Test & Lint

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Install additional testing/linting packages
        pip install black flake8 isort pytest-cov
    
    - name: Run Black (code formatting check)
      run: |
        black --check --diff .
    
    - name: Run isort (import sorting check)  
      run: |
        isort --check-only --diff .
    
    - name: Run Flake8 (linting)
      run: |
        flake8 . --exclude=migrations,__pycache__,venv,env --max-line-length=88
    
    - name: Set up environment variables for tests
      run: |
        echo "SECRET_KEY=test-secret-key-for-ci-$(openssl rand -hex 16)" >> $GITHUB_ENV
        echo "DEBUG=False" >> $GITHUB_ENV
        echo "JWT_SECRET_KEY=test-jwt-secret-$(openssl rand -hex 16)" >> $GITHUB_ENV
        echo "DJANGO_SETTINGS_MODULE=config.settings.testing" >> $GITHUB_ENV
        echo "ALLOWED_HOSTS=localhost,127.0.0.1" >> $GITHUB_ENV
        echo "CORS_ALLOWED_ORIGINS=http://localhost:3000" >> $GITHUB_ENV
    
    - name: Run tests with coverage
      run: |
        python scripts/run_tests.py --coverage
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      if: success()
      with:
        fail_ci_if_error: false
